"""users table

Revision ID: 10b8c1cbd81f
Revises: 
Create Date: 2025-07-24 18:23:47.783439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b8c1cbd81f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('almacenes',
    sa.Column('id_almacen', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_almacen', sa.String(length=50), nullable=False),
    sa.Column('ubicacion', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'inactivo'), nullable=False),
    sa.PrimaryKeyConstraint('id_almacen')
    )
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_categoria', sa.String(length=50), nullable=False),
    sa.Column('descripcion_categoria', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'eliminado'), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('clientes',
    sa.Column('id_cliente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('email')
    )
    op.create_table('grupos',
    sa.Column('id_grupo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_grupo', sa.String(length=50), nullable=False),
    sa.Column('nivel_grupo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'eliminado'), nullable=False),
    sa.PrimaryKeyConstraint('id_grupo')
    )
    op.create_table('proveedores',
    sa.Column('id_proveedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_proveedor', sa.String(length=255), nullable=False),
    sa.Column('contacto', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'eliminado'), nullable=False),
    sa.PrimaryKeyConstraint('id_proveedor')
    )
    op.create_table('unidades_medida',
    sa.Column('id_unidad', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_unidad')
    )
    op.create_table('compras',
    sa.Column('id_compra', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('fecha_compra', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'completada', 'cancelada'), nullable=False),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_compra')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_producto', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_compra', sa.Float(), nullable=False),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.Column('id_unidad_medida', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Float(), nullable=False),
    sa.Column('stock_maximo', sa.Float(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'eliminado'), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_unidad_medida'], ['unidades_medida.id_unidad'], ),
    sa.PrimaryKeyConstraint('id_producto'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('nombreUsuario', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('nivel_usuario', sa.Integer(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('token_recuperacion', sa.String(length=255), nullable=True),
    sa.Column('expira_token', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['nivel_usuario'], ['grupos.id_grupo'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombreUsuario')
    )
    op.create_table('ventas',
    sa.Column('id_venta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('fecha_venta', sa.DateTime(), nullable=False),
    sa.Column('total_venta', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('detalle_compras',
    sa.Column('id_detalle_compra', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id_compra'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_detalle_compra')
    )
    op.create_table('detalle_ventas',
    sa.Column('id_detalle_venta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_detalle_venta')
    )
    op.create_table('imagenes_productos',
    sa.Column('id_imagen', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre_imagen', sa.String(length=255), nullable=False),
    sa.Column('ruta_imagen', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    op.create_table('imagenes_usuarios',
    sa.Column('id_imagen', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_imagen', sa.String(length=255), nullable=False),
    sa.Column('ruta_imagen', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    op.create_table('movimientos_stock',
    sa.Column('id_movimiento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.Column('id_almacen_origen', sa.Integer(), nullable=True),
    sa.Column('id_almacen_destino', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('fecha_movimiento', sa.DateTime(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_almacen_destino'], ['almacenes.id_almacen'], ),
    sa.ForeignKeyConstraint(['id_almacen_origen'], ['almacenes.id_almacen'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_table('stock_almacen',
    sa.Column('id_stock', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_almacen', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad_disponible', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_almacen'], ['almacenes.id_almacen'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_stock')
    )
    op.create_table('alertas_stock',
    sa.Column('id_alerta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_almacen', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(length=255), nullable=False),
    sa.Column('fecha_alerta', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'enviada'), nullable=False),
    sa.ForeignKeyConstraint(['id_almacen'], ['stock_almacen.id_almacen'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_alerta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alertas_stock')
    op.drop_table('stock_almacen')
    op.drop_table('movimientos_stock')
    op.drop_table('imagenes_usuarios')
    op.drop_table('imagenes_productos')
    op.drop_table('detalle_ventas')
    op.drop_table('detalle_compras')
    op.drop_table('ventas')
    op.drop_table('usuarios')
    op.drop_table('productos')
    op.drop_table('compras')
    op.drop_table('unidades_medida')
    op.drop_table('proveedores')
    op.drop_table('grupos')
    op.drop_table('clientes')
    op.drop_table('categorias')
    op.drop_table('almacenes')
    # ### end Alembic commands ###
