"""Fix FK almacenes in alertas_stock

Revision ID: 557f0bd78a78
Revises: 10b8c1cbd81f
Create Date: 2025-07-24 21:39:47.147792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557f0bd78a78'
down_revision = '10b8c1cbd81f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alertas_stock', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('alertas_stock_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'almacenes', ['id_almacen'], ['id_almacen'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alertas_stock', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('alertas_stock_ibfk_1'), 'stock_almacen', ['id_almacen'], ['id_almacen'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
